### ISSUE TITLE
Stripping ampersands from feed?

### ISSUE THREAD

**Issue by jeremycherfas** [OleVik/grav-plugin-twigfeeds#10]
I just noticed that my [latest post](https://stream.jeremycherfas.net/2017/first-gt-of-the-season-and-no-lemon-in-the) is truncated from the first "&" character when displayed by the plugin.

![stream-error](https://cloud.githubusercontent.com/assets/4266172/25071423/c6c39db6-22b6-11e7-9485-277bfae7ecf7.png)

I can see that it is the RSS feed that is not delivering the whole `<title>` and I wonder whether you have any suggestions to change this behaviour.

**Comment by OleVik** [comment]
What settings do you have in twigfeeds.yaml in /user/config/plugins? Need the URL of the feed to replicate.

**Comment by jeremycherfas** [comment]
I've looked again, and the problem is in the outgoing RSS. No problem at your end. Apologies.
