### ISSUE TITLE
custom feeds possible?

### ISSUE THREAD

**Issue by aender6840** [OleVik/grav-plugin-twigfeeds#12]
Hello.

I´m very excited about your GRAV-Plugin Twig Feeds. Is there any way to use it for custom xml feeds like this?
http://ender-zuggal.at.news.atikon.at/content/klienteninfo.xml

I am searching for a solution to implement this custom feed to my new website to look it like this:

http://ender-zuggal.at.news.atikon.at/content/inhalte/klienteninfo/ausgabe_2_2017/so_holen_sie_sich_ihr_geld_vom_finanzamt_zurück/index.html

**Comment by OleVik** [comment]
It will render any valid RSS or Atom feed, which klienteninfo.xml does not appear to be. If you can return it as a regular feed, it can be parsed.
