### ISSUE TITLE
[QUESTION] how to return more values / podcasting feed

### ISSUE THREAD

**Issue by ganar** [OleVik/grav-plugin-twigfeeds#14]
Hello Ole:

Your plugin is great! its doing almost everything I need with it. I'm currently building the site for my podcast and there are values that I need that are not being returned.

[This is a link to  the feed](http://querrecuentos.3ph.com/rss/sound.xml)

Can you give some pointers in how to do this in your code? I think I have to add the definitions in `picofeed/parse/Feed.php` and then in `twigfeeds`, around line 229

These are the additional values I need:

    <itunes:subtitle>
    <media:thumbnail url="http://querrecuentos.3ph.com/images/0042-QC-kashiwamochi-IG.jpg"/>
    <itunes:subtitle>
    <itunes:author>
    <enclosure url="http://dts.podtrac.com/redirect.m4a/cdn.podigee.com/media/podcast_1240_querre_cuentos_episode_6_0019_el_ches.m4a">

I need to be able to set the image url and the audio file url in order to finish building a podcast player.

Thanks a lot for any help you can give me on the subject!

**Comment by OleVik** [comment]
In [v3.2.0](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.2.0) this is facilitated for any tag, provided you iterate over them correctly in Twig. The README is updated with an example of how.

In regards to the specific values listed, you'd have to do this in `twigfeeds.yaml`:

```
twig_feeds:
  - source: http://querrecuentos.3ph.com/rss/sound.xml
    extra_tags:
      - "itunes:subtitle"
      - "itunes:author"
      - "media:thumbnail"
```

`enclosureUrl` is included by default when parsing. To see all the values returned by the plugin, you can do `{{ dump(twig_feeds) }}` in the template where you are iterating over the feeds.

**Comment by ganar** [comment]
@OleVik this worked out great, it is an incredibly useful update. Thanks a lot for your help!

for some reason the `{{ dump(twig_feeds) }}` did notproduce any output in the template. The rest of the `for` statement in the example rendered perfectly, but that bit did not produce anything

**Comment by OleVik** [comment]
Dump() will not produce anything in the template, but it logs to the Debugger, which must be enabled through system.yaml.

**Comment by ganar** [comment]
Hello @OleVik: thanks to your answers I've managed to get almost everything working, but I've not been able to get the `media:thumbnail` URL. This is the image of the debugger:

![home___deliver](https://cloud.githubusercontent.com/assets/431185/26287631/9e506d52-3e4d-11e7-867f-70ab7231137d.png)

As you can see, none of the `@attributes` are shown in the dump, which is very different from the `enclosure`, which shows:

![home___deliver](https://cloud.githubusercontent.com/assets/431185/26287643/e6d4f80e-3e4d-11e7-812a-3435d63c3f7f.png)

1. How do I hace to configure `twigfeeds.yaml` to get this information from the feed?
1. How do I display the URL with `twig` in my template?

**Comment by ganar** [comment]
@OleVik, any pointer on what to modify either on the core of the plugin or on my code would be appreciated.

**Comment by OleVik** [comment]
The problem appears to be that the feed returns a self-closing tag, ie. `<media:thumbnail url="http://querrecuentos.3ph.com/images/0044-QC-jaime.jpg"/>`, whereas the parser expects tags with values inside, eg.: `<media:thumbnail>http://querrecuentos.3ph.com/images/0044-QC-jaime.jpg</media:thumbnail>`.

I am unsure of whether self-closing tags are supported by the parser, PicoFeeds, but to accommodate it you'd have to check that the parser can select an attribute of the self-closing tag and return that rather than the expected wrapped value. If the parser is capable of it, I'd happily accept a PR that facilitates both behaviours.

**Comment by ganar** [comment]
Hi @OleVik:

yes it does:

```
<enclosure url="http://dts.podtrac.com/redirect.m4a/cdn.podigee.com/media/podcast_1240_querre_cuentos_episode_10_0044_jaime_de_cristal.m4a" length="3535439" type="audio/x-m4a"/>
```

The `enclosure` is a self closing tag and _picoFeeds_ expose the `@attributes` inside of it.

**Comment by OleVik** [comment]
I will take a look at implementing this when I get a chance this coming week.

**Comment by ganar** [comment]
Thanks a lot @OleVik: I really appreciate it

**Comment by OleVik** [comment]
I added this in [v3.2.2](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.2.2), see the README for details. Tested with:

```
twig_feeds:
  - source: http://querrecuentos.3ph.com/rss/sound.xml
    end: 1
    extra_tags:
      - "itunes:duration"
      - "media:thumbnail":
        - url
```

**Comment by ganar** [comment]
Hello @OleVik: 

I'm so sorry to bother you, but I cant make it work in this instance, I must be doing something wrong. 

This is my `twigfeeds.yaml`, following your instructions (I had not read the `.yaml` properly in the docs, somehow the last semicolon was missing, thanks a lot for your patience on this matter)


```
enabled: true
cache: true
static_cache: true
debug: false
cache_time: 900
pass_headers: false
twig_feeds:
  -
    source: 'http://querrecuentos.3ph.com/rss/sound.xml'
    name: 'Querre Cuentos'
    start: 0
    end: 20
    extra_tags:
      - "itunes:subtitle"
      - "itunes:author"
      - "itunes:image":
        - href
```

I'm getting an `Illegal offset type` error
```
(…)/www/user/plugins/twigfeeds/Parser.php

16
Whoops\Run handleError
…/user/plugins/twigfeeds/Parser.php119
16
TwigFeeds\Parser parseFeed
…/user/plugins/twigfeeds/twigfeeds.php201
15
Grav\Plugin\TwigFeedsPlugin outputFeeds
…/vendor/symfony/event-dispatcher/EventDispatcher.php184
```

**Comment by ganar** [comment]
The updates for `twigfeeds` are not being read in my control panel. I'm upgrading manually

**Comment by ganar** [comment]
@OleVik for some reason  v3.2.2 is not being downloaded automatically from the plugins repository. I did download the zip file manually and it worked.

Thanks a lot for your patience!

**Comment by OleVik** [comment]
It seems the plugin hasn't updated on the GPM yet, not sure why yet, as the release seems fine. Glad the update works for you.
