### ISSUE TITLE
plugin doesn't reread feed automaticaly

### ISSUE THREAD

**Issue by vadika** [OleVik/grav-plugin-twigfeeds#15]
Hi!
plugin doesn't reread feed automaticaly, 
if I disable caching - throws an exception :(

vadikas@otklik:/var/www/grav/user/data/twigfeeds$ more manifest.json
{
    "config": {
        "user": false,
        "version": "3.2.1"
    },
    "data": {
        "https:\/\/db.otklik.team\/projects\/sar\/issues.atom?c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=assigned_to&c%5B%5D=updated_on&f%5B%5D=status_id&f%5B%5D=tracker_id&f%5B%5D=&group_by=&key=828b2fe41ff4ea0aee7ab738051ba3053e1ff285&op%5Bstatus_id%5D=%2A&op%5Btracker_id%5D=%3D&set_filter=1&utf8=%E2%9C%93&v%5Btracker_id%5D%5B%5D=1": {
            "filename": "fca293b69c25c69e91dc9c7e5f69a124.json",
            "name": "\u0422\u0435\u043a\u0443\u0449\u0438\u0435 \u041f\u0421\u0420",
            "amount": 100,
            "etag": "W\/\"e51353f11c5615dd4c1fd7027d66599a\"",
            "last_modified": "",
            "cache_time": 1,
            "last_checked": 1495485956,
            "last_checked_date": "2017-05-22 23:45:56"
        }
    }
}

**Comment by OleVik** [comment]
This issue wound up on the back-burner for quite a while, but should be fixed in [v3.2.4](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.2.4).
