### ISSUE TITLE
unable to supply format time 

### ISSUE THREAD

**Issue by vadika** [OleVik/grav-plugin-twigfeeds#16]
here is my snippet:

{% for name, feed in twig_feeds %}
    <h5> {{ name }}</h5>
   
    {% for item in feed.items %}
        <h6> {{ item.date.date }} <a href="{{ item.url }}">{{ item.title }}</a></h6>
    {% endfor %}
{% endfor %}

And here is the output, time formatting  with zeroes is not too pretty :(

Текущие ПСР
2017-05-22 14:43:45.000000 ПСР #2 (В работе): нп Снов М 45 лет
2017-05-22 13:07:02.000000 ПСР #1 (Прекращено): Тестовая задача

**Comment by jeremycherfas** [comment]
You could try adding [a filter](https://twig.sensiolabs.org/doc/2.x/filters/date.html)

So:

`<h6> {{ item.date.date | date("d/m/Y") }} <a href="{{ item.url }}">{{ item.title }}</a></h6>`

And even add timezones and things.

**Comment by vadika** [comment]
Thanks, it works!
