### ISSUE TITLE
Enh. idea: support for JSON formatted feeds

### ISSUE THREAD

**Issue by MakaryGo** [OleVik/grav-plugin-twigfeeds#17]
It shouldn't be hard to do, should it?

**Comment by OleVik** [comment]
Whilst not difficult, as JSON is by far a superior format to XML, it is outside of the scope of this plugin. This is for three reasons: First, well-formatted JSON can be parsed by PHP itself, and easily transported to Twig. Second, the library that powers this plugin - picoFeed - does not handle JSON or give any benefit to such parsing. Third, and most importantly. JSON-formatted feeds do not always follow the same naming-conventions as XML do for feeds. If they do, translating them to XML at source or through a middleman would make them immediately usable with the plugin - thus there is not an efficiency-gain from creating this middleman in the plugin itself, rather is a superfluous overhead.

Thus, the only benefit from utilizing the plugin for JSON would be caching. And such caching could more easily be facilitated without the overhead of the plugin and the library.

**Comment by MakaryGo** [comment]
Thank you for broad and clear explanation :) I understood everything even
despite the fact that I'm not a programmer ;)
I'll try process JSON feeds on my own then, I guess.
Cheers!

> --
Kind regards,
Makary
