### ISSUE TITLE
Website crash when url take more than 10 sec to respond.

### ISSUE THREAD

**Issue by m8schmit** [OleVik/grav-plugin-twigfeeds#20]
Hello, i have trouble with this variable : https://github.com/OleVik/grav-plugin-twigfeeds/blob/ffde8851d4a1b0d97623663569af87e0a9b9bf27/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php#L113

After 10 sec, if the url don't respond,  the site crash. Is it possible to handle the error and return an empty array instead ?

**Comment by OleVik** [comment]
It should be, I'll look at adding the TimeoutException from PicoFeeds so it'll gracefully continue instead.

**Comment by OleVik** [comment]
Quick fix implemented in [46d2360](https://github.com/OleVik/grav-plugin-twigfeeds/commit/46d236005ab5642bd5c8332db9f6e9e9df0e50b6), planned to be released soon.
