### ISSUE TITLE
Fetch first image from content

### ISSUE THREAD

**Issue by Keii0** [OleVik/grav-plugin-twigfeeds#21]
Hello,

I'm sorry i'm really new to this so i don't know how to do that and i really tried!

I would like to fetch the first image from the content. I tried to hide the text via css but it's just not enough.

Also, i would like to make categories for my feeds, so i've added "category" in the yaml and now i would like to show only feeds from one category but it doesn't work. How to do that?

Here i tried to replace name with my new category...

```
{% for name, feed in twig_feeds if category == 'news' %}
    <h4>Feed name: {{ name }}</h4>
    <small>Retrieved title: <a href="{{ feed.source }}">{{ feed.title }}</a>, {{ feed.amount }} item(s)</small>
    {% for item in feed.items %}
        <h5>
            <a href="{{ item.url }}">{{ item.title }}</a>
        </h5>
        <time>{{ item.date.date }}</time>
        <p>{{ item.content }}</p>
    {% endfor %}
{% endfor %}
```

Thank you for this awesome plugin! And sorry for being a noob!

**Comment by OleVik** [comment]
Extracting the first image could be done in a variety of ways, but it would help to see some example content before suggesting a way. Could you copy some of the feed's XML into a code block?

I presume this is a custom feed, since you can output a non-standard category item at will. You'll probably need to check for the category in the iteration, rather than the loop-declaration. Something like:

```
{% for name, feed in twig_feeds %}
    {% if feed.category == 'news %}
        Output
    {% endif %}
{% endfor %}
```

**Comment by Keii0** [comment]
Thank you for your very fast reply!

Of course! Here's a feed :

```
		<item>
		<title>Fate/Apocrypha – 24</title>
		<link>https://utw.me/2017/12/28/fate-apocrypha-24/</link>
		<comments>https://utw.me/2017/12/28/fate-apocrypha-24/#comments</comments>
		<pubDate>Thu, 28 Dec 2017 15:44:26 +0000</pubDate>
		<dc:creator><![CDATA[kme]]></dc:creator>
				<category><![CDATA[Anime]]></category>
		<category><![CDATA[apocrypha]]></category>
		<category><![CDATA[Summer 2017]]></category>

		<guid isPermaLink="false">http://utw.me/?p=13186</guid>
		<description><![CDATA[DOWNLOAD: [UTW]_Fate_Apocrypha_-_24_[h264-720p][076597B8].mkv]]></description>
				<content:encoded><![CDATA[<p><img src="https://i.imgur.com/TsFd5PY.jpg" /></p>
<p><strong>DOWNLOAD:</strong> <a href="https://nyaa.si/download/991704.torrent">[UTW]_Fate_Apocrypha_-_24_[h264-720p][076597B8].mkv</a></p>
]]></content:encoded>
			<wfw:commentRss>https://utw.me/2017/12/28/fate-apocrypha-24/feed/</wfw:commentRss>
		<slash:comments>68</slash:comments>
	<post-id xmlns="com-wordpress:feed-additions:1">13186</post-id>	</item>
```

And i just tried what you suggested but still no luck..

Thank you for the help!

**Comment by OleVik** [comment]
If you are testing for category within an item, you'd need to do it in the `{% for item in feed.items %} ... {% endfor %}` loop - notes on that below - to check for it as suggested before, you'd need the channel to have an authoritative `category` like `<category>Newspapers</category>` (see [spec](https://validator.w3.org/feed/docs/rss2.html)).

For items, `<![CDATA[apocrypha]]>` and `<![CDATA[Summer 2017]]>` would have to be checked using the [in containment operator](https://twig.symfony.com/doc/2.x/templates.html#containment-operator) in Twig. The character data ("CDATA") _should_ not be parsed ([source](https://stackoverflow.com/a/2784200/603387)), but your milage may vary on that. To test for one category you would need to select the first on using the `|first`-filter in Twig.

You could fetch the image from `<content:encoded>` using a DOM-parser or with Regular Expressions, but either are really overkill if you could just output the link to the image within the feed item, such as `<media:thumbnail url="http://www.foo.com/keyframe.jpg" width="75" height="50" time="12:05:01.123" />`. The [library](https://github.com/miniflux/picoFeed) used for parsing the feed allows a wide variety of tags, which can be accessed with the [extra_tags](https://github.com/OleVik/grav-plugin-twigfeeds)-property in this plugin.

**Comment by Keii0** [comment]
Actually i'm not using the <category> feed's category, i have my own category that i added in blueprints.yaml

```
        .category:
          type: text
          label: Category
          description: Feed custom category
```

And feed.category doesn't seems to works.

Thank you! I'll try with a DOM-parser then. Just a shame all feeds don't have the media:thumbnail so i have to fetch the first image from content.

I really appreciate the help, thank you!

**Comment by OleVik** [comment]
Is Grav producing the feed for you?

**Comment by Keii0** [comment]
Yes it does!

**Comment by OleVik** [comment]
If a DOM-parser does not solve this, you'd need to leverage Grav's [Feeds](https://github.com/getgrav/grav-plugin-feed) to assign an image to `<media:thumbnail>`.
