### ISSUE TITLE
Check for existence of RSS feed to avoid Pico error

### ISSUE THREAD

**Issue by paulhibbitts** [OleVik/grav-plugin-twigfeeds#26]
This issue came up when the URL feed of an existing RSS feed was changed - due to Pico not handling this situation the generated Pico error brought down the site. It would be a great enhancement if some type of basic error checking on feed URLs could be done before processing by Pico etc.

Thanks so much for this amazing Plugin!
Paul

**Comment by OleVik** [comment]
Will be included in v4.0.0.
