### ISSUE TITLE
Fresh install of Twig Feeds 4.0.0 on Grav 1.6.16 breaks

### ISSUE THREAD

**Issue by bmcsheehy** [OleVik/grav-plugin-twigfeeds#28]
Fresh install results in the following error in grav.log 

[2019-10-15 16:19:13] grav.DEBUG: TwigFeeds: Versions equal, continuing [] []
[2019-10-15 16:19:13] grav.DEBUG: TwigFeeds: Config and manifest equal, continuing [] []
[2019-10-15 16:19:13] grav.DEBUG: TwigFeeds: 2019-10-15 16:25:32 is after 2019-10-15 16:19:13, skip http://rss.nytimes.com/services/xml/rss/nyt/World.xml [] []
[2019-10-15 16:19:13] grav.DEBUG: TwigFeeds: Can't find 149d315c6838bf4ab31c9391ab25fe68.json, writing it [] []
[2019-10-15 16:19:13] grav.CRITICAL: Undefined variable: title - Trace: #0 /var/www/ztest.com/public_html/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError(8, 'Undefined varia...', '/var/www/ztest....', 165) #1 

In the browser it shows. 

/var/www/ztest2.com/public_html/user/plugins/twigfeeds/classes/Parser.php
            }
            
            if (!empty($resource->getResponse()->getLastModified())) {
                $lastModified = $resource->getResponse()->getLastModified();
            } else {
                $lastModified = new DateTime('now');
            }
            $timestamp = $lastModified->getTimestamp();
            if (isset($resource->getResponse()->getHeaders()['ETag'])) {
                $data['etag'] = $resource->getResponse()->getHeaders()['ETag'][0];
            }
            if (!empty($result->getTitle())) {
                $data['title'] = $result->getTitle();
            } else {
                $data['title'] = $args['title'];
            }
            if (isset($args['name'])) {
                $data['name'] = $args['name'];
            } else {
                $data['name'] = $title;
            }
            $data['last_modified'] = $lastModified;
            $data['timestamp'] = $timestamp;
            $data['last_checked'] = $args['now'];
            $data['amount'] = $args['amount'];
            $data['items'] = array();
            $int = 0;
            foreach ($result->toArray()['items'] as $item) {
                $item['lastModified'] = self::getItemDate($item, $lastModified->format('c'));
                $data['items'][] = $item;
                if (++$int >= $args['amount']) {
                    break;
                }
            }
        } catch (Exception $e) {
            throw new \Exception($e);
        }
        $return = array();
        if ($args['cache'] === true) {
            if (empty($path)) {
Arguments
"Undefined variable: title"

We discovered that there was no entry set for the 2nd RSS feed in the "Name" field by default in the plugin configuration. Setting a value in "Name" results in the plugin working again.

**Comment by bmcsheehy** [comment]
<img width="1024" alt="Screen Shot 2019-10-15 at 2 30 47 PM" src="https://user-images.githubusercontent.com/4701230/66863512-c4d58980-ef58-11e9-9d86-f4bb01220cf0.png">

**Comment by OleVik** [comment]
This was a leftover from the previous incarnation of Parser, that oddly escaped testing on both local and live installations. It should be fixed with [v4.0.1](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v4.0.1).
