### ISSUE TITLE
twig_feeds is empty

### ISSUE THREAD

**Issue by gszathmari** [OleVik/grav-plugin-twigfeeds#4]
I am struggling to add this plugin to my website. I have followed all instructions in README.md but the `twig_feeds` variable remains empty. 

The Debug mode shows that the external feeds have been downloaded, however, I cannot access their content by calling `{% for name, feed in twig_feeds %}` as it yields with an empty result. I assume it is because `{{ twig_feeds }}` variable is not populated for some reason.

Other RSS plugins like `Feedme` work fine

**Comment by OleVik** [comment]
If you try `{{ dump(twig_feeds) }}`, do you get the contents there? And is your cache enabled, along with the plugin's cache?

**Comment by gszathmari** [comment]
Thanks @OleVik for the quick response.

I took a few screenshots that show caching is disabled. I have debug mode on and from the little window in the bottom I see that the plugin is reading the elements from the remote feed. Unfortunately, `dump` does not yield any results.

If that helps, I have the Gravstrap theme installed
<img width="976" alt="screen shot 2017-02-13 at 09 32 43" src="https://cloud.githubusercontent.com/assets/4806014/22866785/d76eb848-f1cf-11e6-9ed7-371076c2a30d.png">
<img width="629" alt="screen shot 2017-02-13 at 09 33 24" src="https://cloud.githubusercontent.com/assets/4806014/22866786/d7aff2fe-f1cf-11e6-898c-245aa6707ba3.png">
<img width="829" alt="screen shot 2017-02-13 at 09 33 54" src="https://cloud.githubusercontent.com/assets/4806014/22866787/d7d311bc-f1cf-11e6-88d2-2b7573cc24dc.png">

**Comment by gszathmari** [comment]
I have disabled the Grav-level caching, too, just to make sure it is not the problem. I am still experiencing the issue.
<img width="745" alt="screen shot 2017-02-13 at 09 48 31" src="https://cloud.githubusercontent.com/assets/4806014/22866940/36489df0-f1d2-11e6-8aef-ce3404726936.png">

**Comment by OleVik** [comment]
That the dump returns null points at the underlying issue. Are you using the plugin's default settings, with v2.0.2? Also, what version of Grav are you running?

**Comment by gszathmari** [comment]
Yes, I have removed `user/config/plugins/twigfeeds.yaml` to have a 'clean install'

**Comment by gszathmari** [comment]
Yes, 2.0.2

Regards,
Gabor

**Comment by OleVik** [comment]
I just tested installing v2.0.2 with Grav v1.1.15 on a [live site](https://olevik.me/staging/grav-1.1.15/). Enabling `debug: true` adds the expected output to the debugger, and `{{ dump(twig_feeds) }}` dumps the expected content.

This is using the Twig-structure from the README:

```
{% for name, feed in twig_feeds %}
    <h4>Feed name: {{ name }}</h4>
    <small>Retrieved title: <a href="{{ feed.source }}">{{ feed.title }}</a>, {{ feed.amount }} item(s)</small>
    {% for item in feed.items %}
        <h5>
            <a href="{{ item.url }}">{{ item.title }}</a>
        </h5>
        <time>{{ item.date.date }}</time>
        <p>{{ item.content }}</p>
    {% endfor %}
{% endfor %}
```

Thus I suspect there is a conflict between some settings, or with this plugin and another one. Any chance you could send me a copy of your `user`-folder? If necessary, remove any sensitive content, and clear the cache before zipping it up. You can send it in a private message through Slack to `@olevik`, or through Gitter to `@olevik`.

**Comment by b-f-bs** [comment]
I'm struggling with the same issue. Did you have a chance to find a solution? I'm using the gravstrap plugin which uses the Shortcode Core plugin. If I disable the Shortcode Core I get the twig_feeds displayed but the gravstrap features get lost. Any chance you can tell me how to fix this conflict?

Thanks,
Bjoern

p.s. Great that set up this plugin. Hope I'll get it working soon.

**Comment by OleVik** [comment]
I have not heard back from @gszathmari as of yet, but am in the final stages of testing version 3 of the plugin, which is much more robust and communicative of its processing. The GravStrap-plugin appears to use a page's shortcode-meta (presumably generated YAML) to assign Twig-variables, but it is not apparent to me why this would override the TwigFeeds-plugins Twig-variable, `twig_feeds`, set on a plugin-level.

**Comment by gszathmari** [comment]
Sorry but I have plenty of personal stuff in the user folder. What I can share you is that I have `Gravstrap v1.2.0` theme and `Gravstrap v1.2.2` plugin installed.

**Comment by OleVik** [comment]
I conducted a test by installing Grav v1.1.17, with Admin v1.2.14, GravStrap v1.2.2 (and all its dependencies), GravStrap-theme v1.2.0, and TwigFeeds v2.0.3. I am using the demo-content that ships with GravStrap, and the only change I have made is to `home.html.twig`:

```
{% embed 'partials/base.html.twig' %}
    {% block header %}
    <header id="header">
        {{ jumbotron1 }}
        {{ navbar1 }}
    </header>
    {% endblock %}

    {% block content %}
        {{ content }}
        {{ dump(twig_feeds) }}
        {% for name, feed in twig_feeds %}
            <h4>Feed name: {{ name }}</h4>
            <small>Retrieved title: <a href="{{ feed.source }}">{{ feed.title }}</a>, {{ feed.amount }} item(s)</small>
            {% for item in feed.items %}
                <h5>
                    <a href="{{ item.url }}">{{ item.title }}</a>
                </h5>
                <time>{{ item.date.date }}</time>
                <p>{{ item.content }}</p>
            {% endfor %}
        {% endfor %}
    {% endblock %}
{% endembed %}
```

The dump shows up in the debugger as expected, and the the feeds render as expected, also with `cache: enabled: true` and `twig: cache: true`. Thus I can't replicate a conflict between either GravStrap, ShortCode Core, or GravStrap's dependencies.

How and where are you instantiating the plugin?

From your [previous comment](https://github.com/OleVik/grav-plugin-twigfeeds/issues/4#issuecomment-279257177), @gszathmari, it would appear that you are using the Twig in Markdown. Twig needs to be executed in a template, not in Markdown content, unless you have made special provisions for executing Twig in Markdown.

**Comment by b-f-bs** [comment]
I forgot to mention that I would like to use it on a modular page. Sorry.

I could use your code in home.html.twig without any problems. But when I use it on a modular page I get the null pointer. Can you replicate that?

Thanks,

Bjoern

**Comment by OleVik** [comment]
In a modular page, I can replicate it, and the error stems from the Shortcode Core plugin, which is removing `twig_feeds` from the available Twig Variables. I will open an issue on its repo for further debug.

**Comment by gszathmari** [comment]
I am having the problem on a non-modular page. Could you please send me your .md file?

Thanks

**Comment by OleVik** [comment]
The Markdown in `user/pages/01.home/home.md` is unchanged, but the home-template is changed as described in the [comment above](https://github.com/OleVik/grav-plugin-twigfeeds/issues/4#issuecomment-282552794). As noted, the Twig-loop should be declared in a Twig-template not in a Markdown-file (or a modular child, currently).

**Comment by OleVik** [comment]
@b-f-bs Version [2.0.4](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v2.0.4) allows using `twig_feeds` in varied page-structures, including modules. Tested with GravStrap top-level pages, modular pages, and modular-children.

**Comment by b-f-bs** [comment]
Great! It works. Thank you for the quick solution!

**Comment by OleVik** [comment]
@gszathmari Are you still experiencing the issue? Does [v3.0.1](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.0.1) help?

**Comment by gszathmari** [comment]
Still not working. I created a new template called `components2.html.twig` under `user/themes/gravstrap-theme/templates` with the following contents, but the page is still not showing the feeds

```{% embed 'partials/base.html.twig' %}
    {% block header %}
    <header id="header">
        {{ jumbotron1 }}
        {{ navbar1 }}
    </header>
    {% endblock %}

    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                {{ content }}

XXX
{% for name, feed in twig_feeds %}
        <h4>Feed name: {{ name }}</h4>
        <small>Retrieved title: <a href="{{ feed.source }}">{{ feed.title }}</a>, {{ feed.amount }} item(s)</small>
        {% for item in feed.items %}
                <h5>
                        <a href="{{ item.url }}">{{ item.title }}</a>
                </h5>
                <time>{{ item.date.date }}</time>
                <p>{{ item.content }}</p>
        {% endfor %}
{% endfor %}
YYY
                </div>
            </div>
        </div>
    {% endblock %}
{% endembed %}
```

**Comment by gszathmari** [comment]
After the latest update, the plugin has suddenly started working. All good now :)
