### ISSUE TITLE
Error from some feeds not others

### ISSUE THREAD

**Issue by jeremycherfas** [OleVik/grav-plugin-twigfeeds#7]
Upgraded to v2 on Grav 1.1.16

This feed `https://vaviblog.com/content/all?_t=rss` works perfectly.

But this feed `https://stream.jeremycherfas.net/content/all?_t=rss` causes an error:

`Undefined index: https://stream.jeremycherfas.net/content/all?_t=rss`

In line 79 of twig feeds.php

When I returned to the default feeds (NY Times etc) the error persists.

`Undefined index: http://rss.nytimes.com/services/xml/rss/nyt/World.xml` in line 79

**Comment by OleVik** [comment]
Are you using the `static_cache` and/or `cache`-options? And if so, did you clear the cache when changing the feeds? I think I might need to implement a forced clearing of the cache when changes are made, as the plugin will read an out-of-date manifest that does not match settings anymore.

**Comment by jeremycherfas** [comment]
All seems to be working now. I want to experiment with the cache options to see what works for me. The feed updates only 2 or 3 times a day, so caching will be useful.

**Comment by OleVik** [comment]
The upcoming version 3 will make caching more robust in terms of clearing it, pre-building it, and limiting how often it runs.
