### ISSUE TITLE
Fatal crash with 3.0.1

### ISSUE THREAD

**Issue by jeremycherfas** [OleVik/grav-plugin-twigfeeds#8]
Installed 3.0.1 via the Admin dashboard. Get this error:

````
/Applications/MAMP/htdocs/grav-blog/user/plugins/twigfeeds/Manifest.php
            );
        } else {
            $manifest = array(
                'config' => array(
                    'user' => false
                ),
                'data' => array()
            );
        }
        return $manifest;
    }
 
    /**
     * Compare manifest and settings
     * @param array $manifest Manifest
     * @return array 'state' for state of operation, 'configFileDate' for date changed date of config-file
     */
    public function compare($manifest)
    {
        foreach (array_keys($manifest['data']) as $key) {
            unset($manifest['data'][$key]['name']);
            unset($manifest['data'][$key]['amount']);
            unset($manifest['data'][$key]['etag']);
            unset($manifest['data'][$key]['last_modified']);
            unset($manifest['data'][$key]['last_checked']);
            unset($manifest['data'][$key]['last_checked_date']);
        }
        $feeds = array();
        foreach ($this->twigFeeds as $feed) {
            $feeds[$feed['source']]['filename'] = parse_url($feed['source'], PHP_URL_HOST) . '.json';
            if (isset($feed['cache_time'])) {
                $feeds[$feed['source']]['cache_time'] = $feed['cache_time'];
            } elseif (isset($setting['cache_time'])) {
                $feeds[$feed['source']]['cache_time'] = $setting['cache_time'];
            } else {
                $feeds[$feed['source']]['cache_time'] = $this->cacheTime;
            }
        }
        $return = array(
            'state' => '',
Arguments
"Undefined index: data"
````

`user/config/plugins/twigfeeds.yaml` 
[twigfeeds.yaml.zip](https://github.com/OleVik/grav-plugin-twigfeeds/files/830821/twigfeeds.yaml.zip)

**Comment by OleVik** [comment]
Using your current configuration I get no error thrown from the `compare()`-method of Manifest, but the comparison itself was faulty - it did not include `name` and `amount`. I fixed this in [v3.0.2](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.0.2).

What output do you get in the debugger? And can you confirm that `user/data/twigfeeds/` contains both a `manifest.json` and a `stream.jeremycherfas.net.json`?

**Comment by jeremycherfas** [comment]
The debugger gives the same error as before:

````
/Applications/MAMP/htdocs/grav-blog/user/plugins/twigfeeds/Manifest.php
            );
        } else {
            $manifest = array(
                'config' => array(
                    'user' => false
                ),
                'data' => array()
            );
        }
        return $manifest;
    }
 
    /**
     * Compare manifest and settings
     * @param array $manifest Manifest
     * @return array 'state' for state of operation, 'configFileDate' for date of changed config-file
     */
    public function compare($manifest)
    {
        foreach (array_keys($manifest['data']) as $key) {
            unset($manifest['data'][$key]['etag']);
            unset($manifest['data'][$key]['last_modified']);
            unset($manifest['data'][$key]['last_checked']);
            unset($manifest['data'][$key]['last_checked_date']);
        }
        $feeds = array();
        foreach ($this->twigFeeds as $feed) {
            $feeds[$feed['source']]['filename'] = parse_url($feed['source'], PHP_URL_HOST) . '.json';
            if (isset($feed['name'])) {
                $feeds[$feed['source']]['name'] = $feed['name'];
            }
            if (isset($feed['start'])) {
                $start = $feed['start'];
            } else {
                $start = 0;
            }
            if (isset($feed['end'])) {
                $end = $feed['end'];
            } else {
                $end = 50;
Arguments
"Undefined index: data"
````

This is the line highlighted in the debugger `        foreach (array_keys($manifest['data']) as $key) {`

Manifest.json:

`{"https:\/\/stream.jeremycherfas.net\/content\/all?_t=rss":{"etag":"","last_modified":"Wed, 08 Mar 2017 11:40:24 +0000","filename":"stream.jeremycherfas.net.json","timestamp":1488973224}}`

I confirm that stream.jeremycherfas.net.json is also there.

**Comment by OleVik** [comment]
Is that the entire content of your `manifest.json`? It should be closer to this:

```
{
    "config": {
        "user": true,
        "modified": 1488140877,
        "modified_date": "2017-02-26 21:27:57"
    },
    "data": {
        "https:\/\/stream.jeremycherfas.net\/content\/all?_t=rss": {
            "filename": "stream.jeremycherfas.net.json",
            "name": "Stream",
            "amount": 6,
            "etag": "",
            "last_modified": "Thu, 09 Mar 2017 18:11:59 GMT",
            "cache_time": 900,
            "last_checked": 1489102249,
            "last_checked_date": "2017-03-10 00:30:49"
        }
    }
}
```

This has been the new format since v3, where the manifest is tiered to include more information. The simple resolution should be just clearing the cache, either with `bin/plugin twigfeeds clearcache` or `bin/grav clearcache -all`. You can then rebuild it by either visiting your site, or running `bin/plugin twigfeeds buildcache`.

The reason for the change is to ensure better consistency in data, and more granular control in when the cache is busted or rebuilt. There are also some [new options](https://github.com/OleVik/grav-plugin-twigfeeds#settings-and-usage) you might want to check out.

**Comment by jeremycherfas** [comment]
Yes, it is the entire contents.

I'm pretty sure it dates from before the update to 3.0 and the update will not proceed any further because it throws a massive error in Grav and everything stops.

I'll try clearing the cache, but my local site has cache off.

**Comment by jeremycherfas** [comment]
OK, that solved the problem.

I did both `bin/plugin twigfeeds clearcache` and `bin/grav clearcache --all` and now the site builds and the feed is showing.

I will check on the production site in a few moments.

**Comment by jeremycherfas** [comment]
Oops. On production site, I again get a fatal error, but slightly different.

````
/home/jcgrav/jeremycherfas.net/user/plugins/twigfeeds/Manifest.php
	1	            );
	2	        } else {
	3	            $manifest = array(
	4	                'config' => array(
	5	                    'user' => false
	6	                ),
	7	                'data' => array()
	8	            );
	9	        }
	10	        return $manifest;
	11	    }
	12	 
	13	    /**
	14	     * Compare manifest and settings
	15	     * @param array $manifest Manifest
	16	     * @return array 'state' for state of operation, 'configFileDate' for date of changed config-file
	17	     */
	18	    public function compare($manifest)
	19	    {
	20	        foreach (array_keys($manifest['data']) as $key) {
	21	            unset($manifest['data'][$key]['etag']);
	22	            unset($manifest['data'][$key]['last_modified']);
	23	            unset($manifest['data'][$key]['last_checked']);
	24	            unset($manifest['data'][$key]['last_checked_date']);
	25	        }
	26	        $feeds = array();
	27	        foreach ($this->twigFeeds as $feed) {
	28	            $feeds[$feed['source']]['filename'] = parse_url($feed['source'], PHP_URL_HOST) . '.json';
	29	            if (isset($feed['name'])) {
	30	                $feeds[$feed['source']]['name'] = $feed['name'];
	31	            }
	32	            if (isset($feed['start'])) {
	33	                $start = $feed['start'];
	34	            } else {
	35	                $start = 0;
	36	            }
	37	            if (isset($feed['end'])) {
	38	                $end = $feed['end'];
	39	            } else {
	40	                $end = 50;
Arguments
	1	"array_keys() expects parameter 1 to be array, null given"
````

And this line `foreach (array_keys($manifest['data']) as $key) {` is the one giving the problem.

I have disabled the plugin on the production site.

I have not set any cache time explicitly in the plugin.

**Comment by OleVik** [comment]
One thing to keep in mind is that the TwigFeeds cache is persistent beyond Grav's cache, even when used in the same /cache-folder. That is why `--all` is needed in `bin/grav clearcache --all`; the plugin by design does not register with Grav's clearcache-mechanism in any circumstance, as busting the cache should be deliberately done. I will consider registering the plugin's cache-busting with Grav's simple `clearcache`, so any update to the plugin forces a complete refresh of both manifest and data.

The best approach to use in case of errors or to force a refresh is `bin/plugin twigfeeds clearcache`, or simply changing any part of the configuration for the plugin, as both will force a rebuild of the manifest and subsequently a recheck of the cached data. Even if `cache_time` is not set, it defaults to 900 (15 minutes), as an efficient default.

On your production site the problem seems to be the same: `manifest.json` has not been refreshed to the new format, and thus there is no `$manifest['data']`. A quick fix would be running `bin/plugin twigfeeds clearcache`, and then `bin/plugin twigfeeds buildcache`.

**Comment by jeremycherfas** [comment]
Thanks for the comprehensive explanation; much appreciated.

All is good now.
