### ISSUE TITLE
parseFeed missing argument for path

### ISSUE THREAD

**Issue by b-f-bs** [OleVik/grav-plugin-twigfeeds#9]
Hello Ole,

thank you for the update of the plugin. I tested the new version and got an error in the parseFeed function of Parser.php. As the optional argument path is not used nor set afterwards the default value (false) is passed to the dumpFile function and then to mkdir. I was not able to figure out, what the directory is needed for but can you try to catch that exception?

Thanks,

Bjoern

**Comment by OleVik** [comment]
Parser->parseFeed() should throw an exception if Filesystem->dumpFile() fails, but also `$path = false` is incorrectly specified as the `$path` is indeed required. I will look at ensuring a more proper fallback for `$path`, should have a solution soon, just need to provision my DevEnv.

**Comment by OleVik** [comment]
Actually, `$path = false` is the correct specification, as Parser->parseFeed() can return feed-data without saving it, thus `$path` must be optional. In [v3.0.3](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.0.3) I added a test for an empty `$path`, which will throw an exception, or else continue with trying to call Filesystem->dumpFile().

**Comment by b-f-bs** [comment]
Successfully tested version 3.0.3! (Cache Feeds enabled, static cache disabled)

Though, "Cache Feeds" has to be enabled, otherwise I get a "Class 'TwigFeeds\Exception' not found" Error from Parser.php (line 128).

If "Cache Feeds" is enabled it works. But if I then enable "Static Cache" it throws "Undefined index: data" in line 234 in Manifest.php.

Do you need any more details?

**Comment by OleVik** [comment]
That's the danger of not running in the IDE, I forgot the slash in `\Exception`. Should that be line 243 of Manifest.php? At that point it should compare the existing manifest to determine if it should be busted, but since caching was already enabled `$manifest['data']` should exist. What is the content of your `manifest.json` in /cache/twigfeeds/ at this point?

**Comment by b-f-bs** [comment]
You are right, it is line 243. My manifest.json:

{                                                                                                                                                                         
    "config": {                                                                                                                                                           
        "user": true,                                                                                                                                                     
        "modified": 1490124739,                                                                                                                                           
        "modified_date": "2017-03-21 19:32:19"                                                                                                                            
    },                                                                                                                                                                    
    "data": {                                                                                                                                                             
        "http:\/\/www.ecclesia-bs.de\/web\/category\/predigten\/feed\/": {                                                                                                
            "filename": "www.ecclesia-bs.de.json",                                                                                                                        
            "name": "Predigten Ecclesia Braunschweig",                                                                                                                    
            "amount": 1,                                                                                                                                                  
            "etag": "\"82ad1015df5d4768e4734d70b6b80701\"",                                                                                                               
            "last_modified": "Thu, 16 Mar 2017 19:13:29 GMT",                                                                                                             
            "cache_time": 1000,                                                                                                                                           
            "last_checked": 1490217416,                                                                                                                                   
            "last_checked_date": "2017-03-22 21:16:56"                                                                                                                    
        },                                                                                                                                                                
        "http:\/\/78.47.159.81:8081\/feed.xml": {                                                                                                                         
            "filename": "78.47.159.81.json",                                                                                                                              
            "name": "Predigten Ecclesia Braunschweig",                                                                                                                    
            "amount": 1,                                                                                                                                                  
            "etag": "\"c20-54b550fd931f2-gzip\"",                                                                                                                         
            "last_modified": "Wed, 22 Mar 2017 17:26:33 GMT",                                                                                                             
            "cache_time": 1000,                                                                                                                                           
            "last_checked": 1490217416,                                                                                                                                   
            "last_checked_date": "2017-03-22 21:16:56"                                                                                                                    
        }                                                                                                                                                                 
    }                                                                                                                                                                     
}

Obviously the data key exists. Don know, why it should be unknown. I checked the call of compare. The backtrace gives that it is called in line 135 of twigfeeds.php. Which means that the manifestfile must have been found and read.

            /* Create Manifest */
            $manifestFile = $config['cache_path'] . 'manifest.json';
            if (!file_exists($manifestFile)) {
                $debug ? $this->debug('Manifest does not exist, writing it') : null;
                $content = $manifest->manifestStructure($config['config_file']);
                $content['data'] = $config['twig_feeds'];
                $call = $manifest->writeManifest($manifestFile, $content);
                $debug ? $this->debug($call) : null;
            } else {
                $content = $manifest->readManifest($manifestFile);
                $call = $manifest->compare($content);
 
                /* Pass manifest and configuration in their entirety */
                if ($call['state'] == 'changed') {
                    $callback = $call['state'] . ' ' . $call['configFileDate'];
                    $debug ? $this->debug('Config (' . $callback . ') and manifest unequal, busting cache') : null;
                    $call = $manifest->bustCache();
                    $debug ? $this->debug($call) : null;
                    $debug ? $this->debug('Renewing manifest') : null;
                    $call = $manifest->writeManifest($manifestFile, $content);
                    $debug ? $this->debug($call) : null;
                } else {
                    $debug ? $this->debug('Config and manifest equal, continuing') : null;
                }
            }

**Comment by b-f-bs** [comment]
Another strange thing: I only get the last twig_feed displayed although it should loop through both of them. Here is my template:

{{ content }}
<section id="feeds">
{% for name, feed in twig_feeds %}
    
    
        <div id="feedItem" class="container module">
                {% for item in feed.items %}
                    <h5>
                        <a href="{{ item.url }}">{{ item.title }}</a>
                    </h5>
                    <time>{{ item.date.date }}</time>
                    <p>{{ item.content }}</p>
                {% endfor %}
        </div>
{% endfor %}
</section>

**Comment by OleVik** [comment]
You have named both feeds `Predigten Ecclesia Braunschweig`, so the last feed defined overwrites the first one. Renaming the `http://78.47.159.81:8081/feed.xml`-feed to `Predigten Ecclesia Braunschweig2` works in tests.

**Comment by OleVik** [comment]
[v3.0.4](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.0.4) fixes the incorrect Exception-call, I am working on a solution for busting the cache on plugin update. I presume the above issue to be fixed by forcefully clearing the plugin's cache and renaming either of the feeds' names, if not, please comment with further problems.

**Comment by b-f-bs** [comment]
Thanks. I cleared the cache and renamed one of the feed names. Then it worked.
